#!/bin/bash

mkdir /var/www/html/Rajan-website
sudo echo "<VirtualHost *:80>
    ServerName dilshad.com
    ServerAlias www.dilshad.com
    DocumentRoot /var/www/html/Rajan-website
    ErrorLog ${APACHE_LOG_DIR}/Rajan-website_error.log
    CustomLog ${APACHE_LOG_DIR}/Rajan-website_access.log combined
</VirtualHost>" >> /etc/httpd/conf/httpd.conf

status=$(service httpd configtest 2>&1 | grep "OK" | wc -l)

if [ $status > 0 ]
 then
   sudo service httpd restart
else
   echo "Alert";
fi


